### PR TITLE
Improve meson build system

### PR DESCRIPTION
**Pull request by NathanBnm**
Hi @bluesabre  I made some cleanup to your project structure, especially with meson files. I also created a new folder named extra into the po folder to split translations between the main ones and the metadata ones.

Once you merged this I'll be able to add French translation as well :smile:

### CODE REVIEW

**Comment by bluesabre** [comment]
Overall these changes look fine, but the installation currently fails:

```
bluesabre@elementaryvm:~/Projects/Code/darkbar/build$ sudo ninja install
[0/1] Installing files.
Installing com.github.bluesabre.darkbar to /usr/bin
Installing data/com.github.bluesabre.darkbar.desktop to /usr/share/applications
Installing data/com.github.bluesabre.darkbar.appdata.xml to /usr/share/metainfo
Installing /home/bluesabre/Projects/Code/darkbar/data/icons/16/com.github.bluesabre.darkbar.svg to /usr/share/icons/hicolor/16x16/apps
Installing /home/bluesabre/Projects/Code/darkbar/data/icons/16/com.github.bluesabre.darkbar.svg to /usr/share/icons/hicolor/16x16@2/apps
Installing /home/bluesabre/Projects/Code/darkbar/data/icons/24/com.github.bluesabre.darkbar.svg to /usr/share/icons/hicolor/24x24/apps
Installing /home/bluesabre/Projects/Code/darkbar/data/icons/24/com.github.bluesabre.darkbar.svg to /usr/share/icons/hicolor/24x24@2/apps
Installing /home/bluesabre/Projects/Code/darkbar/data/icons/32/com.github.bluesabre.darkbar.svg to /usr/share/icons/hicolor/32x32/apps
Installing /home/bluesabre/Projects/Code/darkbar/data/icons/32/com.github.bluesabre.darkbar.svg to /usr/share/icons/hicolor/32x32@2/apps
Installing /home/bluesabre/Projects/Code/darkbar/data/icons/48/com.github.bluesabre.darkbar.svg to /usr/share/icons/hicolor/48x48/apps
Installing /home/bluesabre/Projects/Code/darkbar/data/icons/48/com.github.bluesabre.darkbar.svg to /usr/share/icons/hicolor/48x48@2/apps
Installing /home/bluesabre/Projects/Code/darkbar/data/icons/64/com.github.bluesabre.darkbar.svg to /usr/share/icons/hicolor/64x64/apps
Installing /home/bluesabre/Projects/Code/darkbar/data/icons/64/com.github.bluesabre.darkbar.svg to /usr/share/icons/hicolor/64x64@2/apps
Installing /home/bluesabre/Projects/Code/darkbar/data/icons/128/com.github.bluesabre.darkbar.svg to /usr/share/icons/hicolor/128x128/apps
Installing /home/bluesabre/Projects/Code/darkbar/data/icons/128/com.github.bluesabre.darkbar.svg to /usr/share/icons/hicolor/128x128@2/apps
Installing /home/bluesabre/Projects/Code/darkbar/data/com.github.bluesabre.darkbar.gschema.xml to /usr/share/glib-2.0/schemas
Running custom install script '/usr/bin/meson --internal gettext install --subdir=po --localedir=share/locale --pkgname=com.github.bluesabre.darkbar'
Running custom install script '/home/bluesabre/Projects/Code/darkbar/meson/post_install.py'
Failed to run install script '/home/bluesabre/Projects/Code/darkbar/meson/post_install.py'
FAILED: meson-install 
/usr/bin/meson install --no-rebuild
ninja: build stopped: subcommand failed.
```

Attempting the same with the current main branch is successful:
```
bluesabre@elementaryvm:~/Projects/Code/darkbar/build$ sudo ninja install
[0/1] Installing files.
Installing com.github.bluesabre.darkbar to /usr/bin
Installing com.github.bluesabre.darkbar.desktop to /usr/share/applications
Installing com.github.bluesabre.darkbar.appdata.xml to /usr/share/metainfo
Installing /home/bluesabre/Projects/Code/darkbar/data/gschema.xml to /usr/share/glib-2.0/schemas
Installing /home/bluesabre/Projects/Code/darkbar/data/icons/16.svg to /usr/share/icons/hicolor/16x16/apps
Installing /home/bluesabre/Projects/Code/darkbar/data/icons/16.svg to /usr/share/icons/hicolor/16x16@2/apps
Installing /home/bluesabre/Projects/Code/darkbar/data/icons/32.svg to /usr/share/icons/hicolor/32x32/apps
Installing /home/bluesabre/Projects/Code/darkbar/data/icons/32.svg to /usr/share/icons/hicolor/32x32@2/apps
Installing /home/bluesabre/Projects/Code/darkbar/data/icons/48.svg to /usr/share/icons/hicolor/48x48/apps
Installing /home/bluesabre/Projects/Code/darkbar/data/icons/48.svg to /usr/share/icons/hicolor/48x48@2/apps
Installing /home/bluesabre/Projects/Code/darkbar/data/icons/64.svg to /usr/share/icons/hicolor/64x64/apps
Installing /home/bluesabre/Projects/Code/darkbar/data/icons/64.svg to /usr/share/icons/hicolor/64x64@2/apps
Installing /home/bluesabre/Projects/Code/darkbar/data/icons/128.svg to /usr/share/icons/hicolor/128x128/apps
Installing /home/bluesabre/Projects/Code/darkbar/data/icons/128.svg to /usr/share/icons/hicolor/128x128@2/apps
Running custom install script '/usr/bin/meson --internal gettext install --subdir=po --localedir=share/locale --pkgname=com.github.bluesabre.darkbar'
Running custom install script '/usr/bin/python3 /home/bluesabre/Projects/Code/darkbar/meson/post_install.py'
Compiling gsettings schemas...
```

Judging by the output, I'm guessing the failure is due to the shebang being moved down a line on `meson/post_install.py`

**Comment by NathanBnm** [comment]
@bluesabre I assume it's because the `post_install.py` file is not executable. You could try by running `chmod u+x meson/post_install.py` from project root.

I'll check on my side too.

**Comment by bluesabre** [comment]
I tried adjusting chmod and it didn't work. However, removing the blank line did, so went ahead with that change. Thanks for your contribution!

**Comment by NathanBnm** [comment]
It's weird that the ending line is the cause, but good if it works

**Pull request merged**
